// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-lBfJ86loKCM_zC9vMKq8_As1tPLSL0',
    appId: '1:50649385420:web:dcbeb26fcbfb4376ef3569',
    messagingSenderId: '50649385420',
    projectId: 'waterapp-001',
    authDomain: 'waterapp-001.firebaseapp.com',
    storageBucket: 'waterapp-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxmLGzONQx7fPCyX9Fw0a8rZU43Ygr4F8',
    appId: '1:50649385420:android:7300b8da221821bcef3569',
    messagingSenderId: '50649385420',
    projectId: 'waterapp-001',
    storageBucket: 'waterapp-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnL6Mjtm3BvlDXuCYtEd5Yv2hUAhTBMc',
    appId: '1:50649385420:ios:a1ce844b46201993ef3569',
    messagingSenderId: '50649385420',
    projectId: 'waterapp-001',
    storageBucket: 'waterapp-001.firebasestorage.app',
    iosClientId: '50649385420-9ec6pu8v8lieqjq1e5ai1ars64ou0qbg.apps.googleusercontent.com',
    iosBundleId: 'com.srisai.rowater.sriSaiRoWater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjnL6Mjtm3BvlDXuCYtEd5Yv2hUAhTBMc',
    appId: '1:50649385420:ios:a1ce844b46201993ef3569',
    messagingSenderId: '50649385420',
    projectId: 'waterapp-001',
    storageBucket: 'waterapp-001.firebasestorage.app',
    iosClientId: '50649385420-9ec6pu8v8lieqjq1e5ai1ars64ou0qbg.apps.googleusercontent.com',
    iosBundleId: 'com.srisai.rowater.sriSaiRoWater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm-lBfJ86loKCM_zC9vMKq8_As1tPLSL0',
    appId: '1:50649385420:web:0063218f2bcdffe7ef3569',
    messagingSenderId: '50649385420',
    projectId: 'waterapp-001',
    authDomain: 'waterapp-001.firebaseapp.com',
    storageBucket: 'waterapp-001.firebasestorage.app',
  );
}
